- name: [RedHat] get jenkins repo
  get_url: url="http://pkg.jenkins-ci.org/redhat/jenkins.repo" dest=/etc/yum.repos.d/jenkins.repo

- name: [RedHat] set jenkins repo
  command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key

- name: [RedHat] install jenkins
  yum: name=jenkins state=latest enablerepo=jenkins

- name: [RedHat] start jenkins service
  service: name=jenkins state=started
