- name: (RedHat) mkdir svn_repo
  file: path={{ svn_repo }} state=directory recurse=yes owner=vagrant group=vagrant mode=0777
- name: (RedHat) mkdir svn_backup
  file: path={{ svn_backup }} state=directory recurse=yes owner=vagrant group=vagrant mode=0777
- name: (RedHat) mkdir svn_dav
  file: path={{ svn_dav }} state=directory recurse=yes owner=vagrant group=vagrant mode=0777
- name: (RedHat) configure docker-subversion
  template: src=docker-subversion.service.j2 dest=/usr/lib/systemd/system/docker-subversion.service
- name: (RedHat) enable docker-subversion
  service: name=docker-subversion enabled=yes state=started
- name: (RedHat) install httpd-tools
  yum: name=httpd-tools state=latest
