- name: (RedHat) configure docker container services
  template: src=docker-firefox-vnc.service.j2 dest=/usr/lib/systemd/system/{{ docker_firefox_vnc_service_name }}.service

- name: (RedHat) enable docker container services
  service: name={{ docker_firefox_vnc_service_name }} enabled=yes state=started

- name: (RedHat) configure Dockerfile
  template: src=Dockerfile.j2 dest=/tmp/Dockerfile

- name: (RedHat) configure ibus-setup.desktop
  template: src=ibus-setup.desktop.j2 dest=/tmp/ibus-setup.desktop

- name: (RedHat) configure ibus-setup.sh
  template: src=ibus-setup.sh.j2 dest=/tmp/ibus-setup.sh
