# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "relativkreativ/centos-7-minimal"

#	config.vm.network :private_network, ip:"192.168.33.10"
	config.vm.hostname = "localhost"

#	config.vm.network :forwarded_port, guest: 80, host: 10080 # http
#	config.vm.network :forwarded_port, guest: 8080, host: 8080 # http
#	config.vm.network :forwarded_port, guest: 8081, host: 8081 # http

	config.vm.synced_folder ".", "/vagrant", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=600']
	config.vm.synced_folder "../../src", "/var/www/src", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=666']
	config.vm.synced_folder "../../ansible", "/var/ansible", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=666']

	config.ssh.forward_x11 = true

	config.vm.provision :shell, :inline => <<-EOL
	#	yum update -y
		yum install -y epel-release
		yum install -y sshpass
		yum install -y python-devel
		yum install -y git
		easy_install pip
		pip install paramiko PyYAML Jinja2 httplib2
		if [ ! -e /home/vagrant/ansible ]; then
			echo Clone from github...
			cd /home/vagrant
			su vagrant -c "git clone git://github.com/ansible/ansible.git --recursive"
		else
			echo Update from github...
			cd /home/vagrant/ansible
			su vagrant -c "git pull"
		fi
		if ! cat /home/vagrant/.bashrc | grep "source /home/vagrant/ansible/hacking/env-setup" > /dev/null 2>&1; then
			echo Set Ansible Env to .bashrc
			echo "source /home/vagrant/ansible/hacking/env-setup > /dev/null 2>&1" >> /home/vagrant/.bashrc
		fi
		
		ln -s /vagrant/.vagrant/machines/default/virtualbox/private_key /home/vagrant/.ssh/id_rsa
		chown -h vagrant:vagrant /home/vagrant/.ssh/id_rsa
	EOL

end
