# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "relativkreativ/centos-7-minimal"

#	config.vm.network :private_network, ip:"192.168.33.10"
	config.vm.hostname = "localhost"

#	config.vm.network :forwarded_port, guest: 80, host: 10080 # http
#	config.vm.network :forwarded_port, guest: 8080, host: 8080 # http
#	config.vm.network :forwarded_port, guest: 8081, host: 8081 # http

	config.vm.synced_folder ".", "/vagrant", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=600']
	config.vm.synced_folder "../../src", "/var/www/src", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=666']
	config.vm.synced_folder "../../ansible", "/var/ansible", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=666']

	config.ssh.forward_x11 = true

	config.vm.provision :shell, :inline => <<-EOL
	#	yum update -y
		yum install -y epel-release
		yum install -y sshpass
		yum install -y python-devel
		yum install -y git
		easy_install pip
		pip install paramiko PyYAML Jinja2 httplib2
	#	git clone git://github.com/ansible/ansible.git --recursive
	#	cd ansible
	#	source ./hacking/env-setup
	EOL

end
