- name: (RedHat) mkdir required dirs
  file: path={{ item }} state=directory recurse=yes mode=0755
  with_items:
    - "{{ postgresql_for_gitlab_path }}"
    - "{{ redis_for_gitlab_path }}"
    - "{{ gitlab_path }}"

- name: (RedHat) configure docker container services
  template: src={{ item }}.j2 dest=/usr/lib/systemd/system/{{ item }}
  with_items:
    - "docker-postgresql-for-gitlab.service"
    - "docker-redis-for-gitlab.service"
    - "docker-gitlab.service"

- name: (RedHat) enable docker container services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - "docker-postgresql-for-gitlab"
    - "docker-redis-for-gitlab"
    - "docker-gitlab"
