- name: (RedHat) mkdir required dirs
  file: path={{ docker_nginx_data_path }} state=directory recurse=yes mode=0755

- name: (RedHat) configure docker container services
  template: src=docker-nginx.service.j2 dest=/usr/lib/systemd/system/{{ docker_nginx_service_name }}.service

- name: (RedHat) enable docker container services
  service: name={{ docker_nginx_service_name }} enabled=yes state=started
