FROM consol/centos-xfce-vnc

RUN yum -y install ibus-kkc && yum clean all
ADD ibus-setup.desktop /root/Desktop/ibus-setup.desktop
ADD ibus-setup.sh /root/scripts/ibus-setup.sh
RUN chmod +x /root/Desktop/ibus-setup.desktop /root/scripts/ibus-setup.sh
