- name: (RedHat) set elasticsearch.xml to firewalld services
  template: src=firewalld_service_elasticsearch.xml.j2 dest=/etc/firewalld/services/elasticsearch.xml

- name: (RedHat) check if register elasticsearch http service to firewalld
  shell: firewall-cmd --list-service --zone=public | grep elasticsearch
  register: result_for_check
  failed_when: result_for_check.rc not in [0, 1]

- debug: var=result_for_check

- name: (RedHat) register elasticsearch http service to firewalld
  shell: |
    systemctl restart firewalld.service
    firewall-cmd --permanent --add-service elasticsearch
  when: result_for_check.rc == 1
  register: result_for_debug

- debug: var=result_for_debug
