---
- name: npm install gulp-autoprefixer
  shell: |
    if [ ! -e {{ gulp_install_to }}/node_modules/gulp-autoprefixer ]; then
        mkdir -p {{ gulp_install_to }}
        cd {{ gulp_install_to }}
        . /usr/local/nvm/nvm.sh
        npm install gulp-autoprefixer --save-dev --no-bin-links
    fi

#- include: setup-Debian.yml
#  when: "ansible_os_family == 'Debian'"

#- include: setup-RedHat.yml
#  when: "ansible_os_family == 'RedHat'"
