- name: (RedHat) configure docker container services
  template: src=docker-phpldapadmin.service.j2 dest=/usr/lib/systemd/system/{{ docker_phpldapadmin_service_name }}.service

- name: (RedHat) enable docker container services
  service: name={{ docker_phpldapadmin_service_name }} enabled=yes state=started
