# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "relativkreativ/centos-7-minimal"

	config.vm.network :private_network, ip:"192.168.33.10"
	config.vm.hostname = "localhost"

	config.vm.network :forwarded_port, guest: 80, host: 10080 # http
	config.vm.network :forwarded_port, guest: 8080, host: 18080 # http
	config.vm.network :forwarded_port, guest: 3000, host: 3000 # node.js

	config.vm.synced_folder ".", "/vagrant", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=600']
	config.vm.synced_folder "../../src", "/var/www/src", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=666']
	config.vm.synced_folder "../../ansible", "/var/ansible", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=666']

	config.ssh.forward_x11 = true

	config.vm.provision "ansible_local" do |ansible|
#		ansible.playbook = "playbook_sandbox.yml"
#		ansible.playbook = "playbook_docker-subversion.yml"
		ansible.playbook = "playbook_elasticsearch.yml"
		ansible.provisioning_path = "/var/ansible"
		ansible.install = true
		ansible.verbose = false
		
		ansible.inventory_path = "/vagrant/hosts"
		ansible.limit = "all"
	end

end
