# from https://docs.docker.com/engine/installation/ubuntulinux/
- name: (Debian) add the new gpg key
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
- name: (Debian) set docker.list
  template: src=docker.list.ubuntu.j2 dest=/etc/apt/sources.list.d/docker.list
- name: (Debian) update the apt package index
  shell: apt-get update
- name: (Debian) purge the old repo if it exists
  shell: apt-get purge lxc-docker
- name: (Debian) verify that apt is pulling from the right repository
  shell: apt-cache policy docker-engine
- name: (Debian) install the linux-image-extra kernel package
  shell: sudo apt-get install linux-image-extra-$(uname -r)
- name: (Debian) install docker
  apt: name=docker-engine state=installed
- name: (Debian) enable docker
  service: name=docker enabled=yes state=started
