---
- hosts: servers
  become: true
  user: vagrant
  vars:
    scala_install_to: "/opt"
    scala_install_version: "2.11.8"
    spark_install_to: "/opt"
    spark_install_version: "1.6.1"
  roles:
    - scala
    - spark
