---
- hosts: servers
  sudo: true
  user: vagrant
  vars:
    svn_repo: "/var/svn/svn"
    svn_backup: "/var/svn/svn-backup"
    svn_dav: "/var/svn/dav_svn"
    svn_port_http: 8080
    svn_port_https: 8443
  roles:
    - docker-subversion
