---
- hosts: servers
  become: true
  user: vagrant
  vars:
    docker_nginx_service_name: "docker-nginx"
    docker_nginx_container_name: "nginx"
    docker_nginx_data_path: "/var/docker-nginx/data"
    docker_nginx_conf_path: "/var/docker-nginx/conf"
    docker_nginx_port: 8081
  roles:
    - docker-nginx
