---
- hosts: servers
  become: true
  user: vagrant
  vars:
    docker_elasticsearch_service_name: "docker-elasticsearch"
    docker_elasticsearch_container_name: "elasticsearch"
    docker_elasticsearch_http_port: 9200
    docker_elasticsearch_transport_port: 9300
  roles:
    - docker-elasticsearch
