---
- hosts: servers
  become: true
  user: vagrant
  vars:
    docker_elasticsearch_service_name: "docker-elasticsearch"
    docker_elasticsearch_container_name: "elasticsearch"
    docker_elasticsearch_version: "2.2.0"
    docker_elasticsearch_http_port: 9200
    docker_elasticsearch_transport_port: 9300
    docker_elasticsearch_conf_path: "/var/docker-elasticsearch/conf"
    docker_elasticsearch_log_path: "/var/docker-elasticsearch/logs"
  roles:
    - docker-elasticsearch
