# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "relativkreativ/centos-7-minimal"

	config.vm.network :private_network, ip:"192.168.33.10"
	config.vm.hostname = "localhost"

	config.vm.network :forwarded_port, guest: 4040, host: 14040 # SparkUI
	config.vm.network :forwarded_port, guest: 8080, host: 18080 # Spark Master

	config.vm.synced_folder ".", "/vagrant", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=600']
	config.vm.synced_folder "../../src", "/var/www/src", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=666']
	config.vm.synced_folder "../../ansible", "/var/ansible", :create => true, :owner => 'vagrant', :group => 'vagrant', :mount_options => ['dmode=777', 'fmode=666']

	config.ssh.forward_x11 = true

	config.vm.provision :shell, :inline => <<-EOL
		yum install -y epel-release
		yum install -y ansible
		if [ ! -e /home/vagrant/.ssh/id_rsa ]; then
			ln -s /vagrant/.vagrant/machines/default/virtualbox/private_key /home/vagrant/.ssh/id_rsa
			chown -h vagrant:vagrant /home/vagrant/.ssh/id_rsa
		fi
		cd /var/ansible
		ansible-playbook -i /vagrant/hosts playbook_spark.yml
	EOL

end
