- name: git clone pico
  shell: |
    if [ ! -e /var/www/src/Pico ]; then
        cd /var/www/src
        git clone https://github.com/picocms/Pico.git
        cd Pico
        /usr/local/bin/composer install
    fi

- include: setup-Debian.yml
  when: "ansible_os_family == 'Debian'"

- include: setup-RedHat.yml
  when: "ansible_os_family == 'RedHat'"
